# a good example is: https://github.com/boostorg/hana/blob/master/.travis.yml
language: c++
compiler:
    - gcc
matrix:
  exclude:
    - os: linux
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
before_install:
  - echo $TRAVIS_OS_NAME
  - echo $LANG
  - echo $LC_ALL
  - echo $CXX
  - which $CXX
  - which $CC
  - $CXX --version
  - python --version
  - git submodule update --init
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq
  - sudo apt-get -y install qt55[QTPACKAGE]
  #- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  #- sudo apt-get update -qq
  #- sudo apt-get install qtbase5-dev
  #- sudo apt-get install qt5-default
  - which qmake
  - qmake --version
  - /opt/qt55/bin/qmake --version
before_script: ls
script:
  - source /opt/qt55/bin/qt55-env.sh
  - /opt/qt55/bin/qmake CONFIG+=debug CONFIG+=SAMPLEAPP DEFINES+=QDEBUG_NOQUOTE_NOT_AVAILABLE qttpserver.pro
  - make
branches:
  only:
    - master
os:
  - linux
  